../tb/shared_pkg.sv
../rtl/APB_Master.sv
../rtl/APB_Controller.sv
../rtl/AES_APB_UART_Bridge.sv
../rtl/Mux.sv
../rtl/UART/*.sv
../rtl/UART/FIFO/*.sv
../rtl/pos_edge_det.sv
../rtl/APB_RegFile/*.sv
../rtl/AES/encryptRound.v
../rtl/AES/mixColumns.v
../rtl/AES/sbox.v
../rtl/AES/shiftRows.v
../rtl/AES/subBytes.v
../rtl/AES/addRoundKey.v
../rtl/AES/keyExpansion.v
../rtl/AES/AES_Encrypt.v
../bfms/APB_controller_if.sv
../bfms/AES_if.sv
../bfms/SYSCTRL_bfm.sv
../bfms/APB_bfm.sv
../tb/bridge_pkg.sv
../tb/top.sv
../tb/aes_encrypt.c