vlib work
vlog -sv tb/packages/tx_defs_pkg.sv tb/ref_model/B2L_modelling.sv tb/ref_model/LFSR_modelling.sv tb/ref_model/per_lane_id_modelling.sv tb/ref_model/TX_controller_modelling.sv tb/packages/tx_tb_pkg.sv tb/ref_model/dut_copy/dut_B2L_modelling.sv tb/ref_model/dut_copy/dut_LFSR_modelling.sv tb/ref_model/dut_copy/dut_per_lane_id_modelling.sv tb/ref_model/dut_copy/dut_TX_controller_modelling.sv tb/ref_model/dut_copy/dut_tx_tb_pkg.sv tb/interfaces/*.sv tb/assertions/tx_sva.sv tb/top/model_dut_stub.sv tb/top/tx_tb_top.sv +incdir+tb/packages +incdir+tb/interfaces +incdir+tb/seq_items +incdir+tb/seq_lib +incdir+tb/agents/rdi_agent +incdir+tb/agents/ltsm_agent +incdir+tb/agents/tx2link_agent +incdir+tb/ref_model +incdir+tb/ref_model/dut_copy +incdir+tb/scoreboard +incdir+tb/coverage +incdir+tb/env +incdir+tb/tests -l compile.log
vlog -sv -suppress 7033 \
  tb/packages/tx_defs_pkg.sv \
  tb/packages/tx_tb_pkg.sv \
  tx_path/synchonizer.sv \
  tx_path/ucie_mux_4_to_1.sv \
  tx_path/ucie_shift_register_b2l.sv \
  tx_path/ucie_byte_to_lane_decoder.sv \
  tx_path/lane_id_register.sv \
  tx_path/mux_2_1.sv \
  tx_path/reversal.sv \
  tx_path/clock_divider.sv \
  tx_path/LFSR_pattern_generator.sv \
  tx_path/tx_LFSR.sv \
  tx_path/tx_LFSR_top.sv \
  tx_path/fifo.sv \
  tx_path/serializer.sv \
  tx_path/empty_decoder.sv \
  tx_path/pattern_generation_decoder.sv \
  tx_path/clk_valid_pattern_generation.sv \
  tx_path/drivers.sv \
  tx_path/ucie_byte_to_lane.sv \
  tx_path/tx_controller.sv \
  tx_path/tx_path.sv \
  tx_path/per_lane_id_generator_top.svh \
  tb/interfaces/*.sv \
  tb/assertions/tx_sva.sv \
  tb/top/tx_dut_rtl_wrapper.sv \
  tb/top/tx_tb_top.sv \
  +incdir+tx_path \
  +incdir+tb/packages \
  +incdir+tb/interfaces \
  +incdir+tb/seq_items \
  +incdir+tb/seq_lib \
  +incdir+tb/agents/rdi_agent \
  +incdir+tb/agents/ltsm_agent \
  +incdir+tb/agents/tx2link_agent \
  +incdir+tb/ref_model \
  +incdir+tb/scoreboard \
  +incdir+tb/coverage \
  +incdir+tb/env \
  +incdir+tb/tests