// ****************************************************************************
// *                                                                          *
// * Copyright (c) 2014-2015 Synopsys Inc. All rights reserved.               *
// *                                                                          *
// * Synopsys Proprietary and Confidential. This file contains confidential   *
// * information and the trade secrets of Synopsys Inc. Use, disclosure, or   *
// * reproduction is prohibited without the prior express written permission  *
// * of Synopsys, Inc.                                                        *
// *                                                                          *
// * Synopsys, Inc.                                                           *
// * 700 East Middlefield Road                                                *
// * Mountain View, California 94043                                          *
// * (800) 541-7737                                                           *
// *                                                                          *
// ****************************************************************************


package LTSM_pkg;
    import uvm_pkg::*;
    `include "uvm_macros.svh"

    // shared packages
    `include "shared_ltsm_pkg.svh"

    // Sequence Items
    `include "sequence_items/LTSM_controllers_sequence_item.sv"
    `include "sequence_items/ltsm_rdi_sequence_item.sv"
    `include "sequence_items/rx_fsm_sb_sequence_item.svh"
    `include "sequence_items/tx_fsm_sb_sequence_item.svh"
    
    // Sequencers
    `include "sequencers/LTSM_controllers_sqr.sv"
    `include "sequencers/ltsm_rdi_sequencer.sv"
    `include "sequencers/rx_fsm_sb_sequencer.svh"
    `include "sequencers/tx_fsm_sb_sequencer.svh"
    `include "virtual_sequencer.svh"
    
    // Configuration Objects
    `include "env_config.svh"
    `include "agent_config.svh"
    `include "controller_agent_config.sv"
    `include "rdi_agent_config.sv"

    // Monitors
    `include "monitors/LTSM_monitor_base.svh"
    `include "monitors/LTSM_controllers_monitor.sv"
    `include "monitors/ltsm_rdi_monitor.sv"
    `include "monitors/rx_fsm_sb_monitor.svh"
    `include "monitors/tx_fsm_sb_monitor.svh"
    
    // Drivers
    `include "drivers/LTSM_driver_base.svh"
    `include "drivers/LTSM_controllers_driver.sv"
    `include "drivers/ltsm_rdi_driver.sv"
    `include "drivers/rx_fsm_sb_driver.svh"
    `include "drivers/tx_fsm_sb_driver.svh"
    
    // Agents 
    `include "ltsm_rdi_agent.sv"
    `include "rx_fsm_sb_agent.svh"
    `include "tx_fsm_sb_agent.svh"
    `include "TX_RX_controllers_agent.sv"
    
    // model
    `include "model/fsm_context.svh"
    `include "model/state.svh"
    `include "model/statetransition_rx.svh"
    `include "model/statetransition_tx.svh"
    `include "model/mbtrain_rx_valvref.svh"
    `include "model/mbtrain_rx_valtrainvref.svh"
    `include "model/mbtrain_rx_valtraincenter.svh"
    `include "model/mbtrain_rx_dtc2.svh"
    `include "model/mbtrain_rx_dtc1.svh"
    `include "model/mbtrain_rx_datavref.svh"
    `include "model/mbtrain_rx_datatrainvref.svh"
    `include "model/mbtrain_rx_rxclkcal.svh"
    `include "model/mbtrain_rx_repair.svh"
    `include "model/mbtrain_tx_repair.svh"
    `include "model/mbtrain_tx_linkspeed.svh"
    `include "model/mbtrain_rx_speedidle.svh"
    `include "model/mbtrain_tx_speedidle.svh"
    `include "model/mbtrain_tx_dtc2.svh"
    `include "model/mbtrain_rx_linkspeed.svh"
    `include "model/mbtrain_tx_txselfcal.svh"
    `include "model/mbtrain_tx_datatrainvref.svh"
    `include "model/mbtrain_tx_datavref.svh"
    `include "model/mbtrain_tx_dtc1.svh"
    `include "model/mbtrain_tx_rxclkcal.svh"
    `include "model/mbtrain_tx_rxdeskew.svh"
    `include "model/mbtrain_tx_valtraincenter.svh"
    `include "model/mbtrain_tx_valtrainvref.svh"
    `include "model/mbtrain_tx_valvref.svh"
    `include "model/mbtrain_tx_rxdeskew.svh"
    `include "model/mbtrain_tx_txselfcal.svh"
    `include "model/reset_state_rx.sv"
    `include "model/reset_state_tx.sv"
    `include "model/sbinit_state_rx.sv"
    `include "model/sbinit_state_tx.sv"
    `include "model/mbinit_repairmb_state_rx.sv"
    `include "model/mbinit_cal_state_rx.sv"
    `include "model/mbinit_cal_state_tx.sv"
    `include "model/mbinit_param_state_rx.sv"
    `include "model/mbinit_param_state_tx.sv"
    `include "model/mbinit_repairclk_state_rx.sv"
    `include "model/mbinit_repairclk_state_tx.sv"
    `include "model/mbinit_repairmb_state_tx.sv"
    `include "model/mbinit_repairval_state_rx.sv"
    `include "model/mbinit_repairval_state_tx.sv"
    `include "model/mbinit_reversalmb_state_rx.sv"
    `include "model/mbinit_reversalmb_state_tx.sv"
    `include "model/trainerror_rx.svh"
    `include "model/trainerror_tx.svh"
    `include "model/linkinit_tx.sv"
    `include "model/linkinit_rx.sv"
    `include "model/l1_rx.sv"
    `include "model/l1_tx.sv"

    // Environment
    `include "env.svh"
    
    // mbtrain base sequences
    `include "sequences/mbtrain/controllers_done.svh"
    `include "sequences/mbtrain/mbtrain_datatrainvref_rx_endhandshake.svh"
    `include "sequences/mbtrain/mbtrain_datatrainvref_rx_starthandshake.svh"
    `include "sequences/mbtrain/mbtrain_datatrainvref_tx_endhandshake.svh"
    `include "sequences/mbtrain/mbtrain_datatrainvref_tx_starthandshake.svh"
    `include "sequences/mbtrain/mbtrain_datavref_rx_endhandshake.svh"
    `include "sequences/mbtrain/mbtrain_datavref_rx_starthandshake.svh"
    `include "sequences/mbtrain/mbtrain_datavref_speedidle_tx.svh"
    `include "sequences/mbtrain/mbtrain_datavref_tx_endhandshake.svh"
    `include "sequences/mbtrain/mbtrain_datavref_tx_starthandshake.svh"
    `include "sequences/mbtrain/mbtrain_dtc1_rx_endhandshake.svh"
    `include "sequences/mbtrain/mbtrain_dtc1_rx_starthandshake.svh"
    `include "sequences/mbtrain/mbtrain_dtc1_tx_endhandshake.svh"
    `include "sequences/mbtrain/mbtrain_dtc1_tx_starthandshake.svh"
    `include "sequences/mbtrain/mbtrain_dtc2_rx_endhandshake.svh"
    `include "sequences/mbtrain/mbtrain_dtc2_rx_starthandshake.svh"
    `include "sequences/mbtrain/mbtrain_dtc2_tx_endhandshake.svh"
    `include "sequences/mbtrain/mbtrain_dtc2_tx_starthandshake.svh"
    `include "sequences/mbtrain/mbtrain_linkspeed_linkinit_tx.svh"
    `include "sequences/mbtrain/mbtrain_linkspeed_phyretrain_rx.svh"
    `include "sequences/mbtrain/mbtrain_linkspeed_repair_tx.svh"
    `include "sequences/mbtrain/mbtrain_linkspeed_rx_endhandshake.svh"
    `include "sequences/mbtrain/mbtrain_linkspeed_rx_error_req.svh"
    `include "sequences/mbtrain/mbtrain_linkspeed_rx_repair.svh"
    `include "sequences/mbtrain/mbtrain_linkspeed_rx_speeddegrade.svh"
    `include "sequences/mbtrain/mbtrain_linkspeed_rx_starthandshake.svh"
    `include "sequences/mbtrain/mbtrain_linkspeed_speedidle_tx.svh"
    `include "sequences/mbtrain/mbtrain_linkspeed_tx_datatoclockstart.svh"
    `include "sequences/mbtrain/mbtrain_linkspeed_tx_error_rsp.svh"
    `include "sequences/mbtrain/mbtrain_linkspeed_tx_phyretrainreq.svh"
    `include "sequences/mbtrain/mbtrain_linkspeed_tx_starthandshake.svh"
    `include "sequences/mbtrain/mbtrain_repair_r"
    `include "sequences/mbtrain/mbtrain_repair_rx_degrade_0.svh"
    `include "sequences/mbtrain/mbtrain_repair_rx_degrade_0_3.svh"
    `include "sequences/mbtrain/mbtrain_repair_rx_degrade_0_7.svh"
    `include "sequences/mbtrain/mbtrain_repair_rx_degrade_0_15.svh"
    `include "sequences/mbtrain/mbtrain_repair_rx_degrade_4_7.svh"
    `include "sequences/mbtrain/mbtrain_repair_rx_degrade_8_15.svh"
    `include "sequences/mbtrain/mbtrain_repair_rx_endhandshake.svh"
    `include "sequences/mbtrain/mbtrain_repair_rx_starthandshake.svh"
    `include "sequences/mbtrain/mbtrain_repair_tx_applydegrade.svh"
    `include "sequences/mbtrain/mbtrain_repair_tx_endhandshake.svh"
    `include "sequences/mbtrain/mbtrain_repair_tx_starthandshake.svh"
    `include "sequences/mbtrain/mbtrain_repair_tx_txselfcal_tx.svh"
    `include "sequences/mbtrain/mbtrain_rxclkcal_rx_endhandshake.svh"
    `include "sequences/mbtrain/mbtrain_rxclkcal_rx_starthandshake.svh"
    `include "sequences/mbtrain/mbtrain_rxclkcal_tx_endhandshake.svh"
    `include "sequences/mbtrain/mbtrain_rxclkcal_tx_starthandshake.svh"
    `include "sequences/mbtrain/mbtrain_rxdeskew_rx_endhandshake.svh"
    `include "sequences/mbtrain/mbtrain_rxdeskew_rx_starthandshake.svh"
    `include "sequences/mbtrain/mbtrain_rxdeskew_tx_endhandshake.svh"
    `include "sequences/mbtrain/mbtrain_rxdeskew_tx_starthandshake.svh"
    `include "sequences/mbtrain/mbtrain_speedidle_rx_endhandshake.svh"
    `include "sequences/mbtrain/mbtrain_speedidle_tx_endhandshake.svh"
    `include "sequences/mbtrain/mbtrain_txselfcal_calibration_tx.svh"
    `include "sequences/mbtrain/mbtrain_txselfcal_rx_endhandshake.svh"
    `include "sequences/mbtrain/mbtrain_txselfcal_tx_endhandshake.svh"
    `include "sequences/mbtrain/mbtrain_valtraincenter_rx_endhandshake.svh"
    `include "sequences/mbtrain/mbtrain_valtraincenter_rx_starthandshake.svh"
    `include "sequences/mbtrain/mbtrain_valtraincenter_tx_endhandshake.svh"
    `include "sequences/mbtrain/mbtrain_valtraincenter_tx_starthandshake.svh"
    `include "sequences/mbtrain/mbtrain_valtrainvref_rx_endhandshake.svh"
    `include "sequences/mbtrain/mbtrain_valtrainvref_rx_starthandshake.svh"
    `include "sequences/mbtrain/mbtrain_valtrainvref_tx_endhandshake.svh"
    `include "sequences/mbtrain/mbtrain_valtrainvref_tx_starthandshake.svh"
    `include "sequences/mbtrain/mbtrain_valvref_rx_endhandshake.svh"
    `include "sequences/mbtrain/mbtrain_valvref_rx_starthandshake.svh"
    `include "sequences/mbtrain/mbtrain_valvref_tx_endhandshake.svh"
    `include "sequences/mbtrain/mbtrain_valvref_tx_starthandshake.svh"
    `include "sequences/mbtrain/rx_done.svh"
    `include "sequences/mbtrain/tx_done.svh"

    // results base sequences
    `include "sequences/results/result_fail_0_3_8_15.svh"
    `include "sequences/results/result_fail_0_7.svh"
    `include "sequences/results/result_fail_4_15.svh"
    `include "sequences/results/result_fail_8_15.svh"
    `include "sequences/results/result_success.svh"
    `include "sequences/results/result_all_fail.svh"

    // rxinit_datasweep base sequences
    `include "sequences/rxinit_datasweep/mbtrain_rxinit_datasweep_rx_lfsrclear.svh"
    `include "sequences/rxinit_datasweep/mbtrain_rxinit_datasweep_rx_pattern.svh"
    `include "sequences/rxinit_datasweep/mbtrain_rxinit_datasweep_rx_result.svh"
    `include "sequences/rxinit_datasweep/mbtrain_rxinit_datasweep_rx_starthandshake.svh"
    `include "sequences/rxinit_datasweep/mbtrain_rxinit_datasweep_rx_sweep.svh"
    `include "sequences/rxinit_datasweep/mbtrain_rxinit_datasweep_tx_end.svh"
    `include "sequences/rxinit_datasweep/mbtrain_rxinit_datasweep_tx_lfsrclear.svh"
    `include "sequences/rxinit_datasweep/mbtrain_rxinit_datasweep_tx_pattern.svh"
    `include "sequences/rxinit_datasweep/mbtrain_rxinit_datasweep_tx_result.svh"
    `include "sequences/rxinit_datasweep/mbtrain_rxinit_datasweep_tx_result_rsp_allfail.svh"
    `include "sequences/rxinit_datasweep/mbtrain_rxinit_datasweep_tx_result_rsp_fail_0_3_8_15.svh"
    `include "sequences/rxinit_datasweep/mbtrain_rxinit_datasweep_tx_result_rsp_fail_0_7.svh"
    `include "sequences/rxinit_datasweep/mbtrain_rxinit_datasweep_tx_result_rsp_fail_4_15.svh"
    `include "sequences/rxinit_datasweep/mbtrain_rxinit_datasweep_tx_result_rsp_fail_8_15.svh"
    `include "sequences/rxinit_datasweep/mbtrain_rxinit_datasweep_tx_result_rsp_succes.svh"
    `include "sequences/rxinit_datasweep/mbtrain_rxinit_datasweep_tx_starthandshake.svh"

    // txinit_datasweep base sequences
    `include "sequences/txinit_datasweep/mbtrain_txinit_datasweep_rx_endhandshake.svh"
    `include "sequences/txinit_datasweep/mbtrain_txinit_datasweep_rx_lfsrclear.svh"
    `include "sequences/txinit_datasweep/mbtrain_txinit_datasweep_rx_pattern.svh"
    `include "sequences/txinit_datasweep/mbtrain_txinit_datasweep_rx_result.svh"
    `include "sequences/txinit_datasweep/mbtrain_txinit_datasweep_rx_starthandshake.svh"
    `include "sequences/txinit_datasweep/mbtrain_txinit_datasweep_tx_endhandshake.svh"
    `include "sequences/txinit_datasweep/mbtrain_txinit_datasweep_tx_lfsrclear.svh"
    `include "sequences/txinit_datasweep/mbtrain_txinit_datasweep_tx_pattern.svh"
    `include "sequences/txinit_datasweep/mbtrain_txinit_datasweep_tx_result.svh"
    `include "sequences/txinit_datasweep/mbtrain_txinit_datasweep_tx_result_rsp_allfail.svh"
    `include "sequences/txinit_datasweep/mbtrain_txinit_datasweep_tx_result_rsp_fail_0_3_8_15.svh"
    `include "sequences/txinit_datasweep/mbtrain_txinit_datasweep_tx_result_rsp_fail_0_7.svh"
    `include "sequences/txinit_datasweep/mbtrain_txinit_datasweep_tx_result_rsp_fail_4_15.svh"
    `include "sequences/txinit_datasweep/mbtrain_txinit_datasweep_tx_result_rsp_fail_8_15.svh"
    `include "sequences/txinit_datasweep/mbtrain_txinit_datasweep_tx_result_rsp_succes.svh"

    //common base sequences
    `include "sequences/nothing_rx.svh"
    `include "sequences/nothing_tx.svh"
    `include "sequences/trainerror_exitreset.svh"
    `include "sequences/trainerror_rx_rsp.svh"
    `include "sequences/trainerror_tx_rsp.svh"
    `include "sequences/trainerror_rx_starthandshake.svh"

    // virtual Sequences
    `include "virtual_sequence/virtual_sequence_base.svh"

    // rxinit_datasweep
    `include "virtual_sequence/rxinit_datasweep/mbtrain_rxinit_datasweep_allfail.svh"
    `include "virtual_sequence/rxinit_datasweep/mbtrain_rxinit_datasweep_fail_0_3_8_15.svh"
    `include "virtual_sequence/rxinit_datasweep/mbtrain_rxinit_datasweep_fail_0_7.svh"
    `include "virtual_sequence/rxinit_datasweep/mbtrain_rxinit_datasweep_fail_4_15.svh"
    `include "virtual_sequence/rxinit_datasweep/mbtrain_rxinit_datasweep_fail_8_15.svh"
    `include "virtual_sequence/rxinit_datasweep/mbtrain_rxinit_datasweep_success.svh"

    // txinit_datasweep
    `include "virtual_sequence/txinit_datasweep/mbtrain_txinit_datasweep_allfail.svh"
    `include "virtual_sequence/txinit_datasweep/mbtrain_txinit_datasweep_fail_0_3_8_15.svh"
    `include "virtual_sequence/txinit_datasweep/mbtrain_txinit_datasweep_fail_0_7.svh"
    `include "virtual_sequence/txinit_datasweep/mbtrain_txinit_datasweep_fail_4_15.svh"
    `include "virtual_sequence/txinit_datasweep/mbtrain_txinit_datasweep_fail_8_15.svh"
    `include "virtual_sequence/txinit_datasweep/mbtrain_txinit_datasweep_success.svh"
    `include "virtual_sequence/txinit_datasweep/mbtrain_txinit_datasweep_txallfail_rxpass.svh"
    `include "virtual_sequence/txinit_datasweep/mbtrain_txinit_datasweep_txfail_0_7_rxpass.svh"
    `include "virtual_sequence/txinit_datasweep/mbtrain_txinit_datasweep_txnotallfail_rxallfail.svh"
    `include "virtual_sequence/txinit_datasweep/mbtrain_txinit_datasweep_txpass_rxfail_0_7.svh"
    `include "virtual_sequence/txinit_datasweep/mbtrain_txinit_datasweep_txpass_rxfallfail.svh"

    // mbtrain
    `include "virtual_sequence/mbtrain/mbtrain_datatrainvref_looptillerror.svh"
    `include "virtual_sequence/mbtrain/mbtrain_datatrainvref_success.svh"
    `include "virtual_sequence/mbtrain/mbtrain_datatrainvref_timeout.svh"
    `include "virtual_sequence/mbtrain/mbtrain_datatrainvref_trainerror.svh"
    `include "virtual_sequence/mbtrain/mbtrain_datavref_looptillerror.svh"
    `include "virtual_sequence/mbtrain/mbtrain_datavref_success.svh"
    `include "virtual_sequence/mbtrain/mbtrain_datavref_timeout.svh"
    `include "virtual_sequence/mbtrain/mbtrain_datavref_trainerror.svh"
    `include "virtual_sequence/mbtrain/mbtrain_dtc1_success.svh"
    `include "virtual_sequence/mbtrain/mbtrain_dtc1_timeout.svh"
    `include "virtual_sequence/mbtrain/mbtrain_dtc1_trainerror.svh"
    `include "virtual_sequence/mbtrain/mbtrain_dtc2_success.svh"
    `include "virtual_sequence/mbtrain/mbtrain_dtc2_timeout.svh"
    `include "virtual_sequence/mbtrain/mbtrain_dtc2_trainerror.svh"
    `include "virtual_sequence/mbtrain/mbtrain_linkspeed_phyretrain_lanepossible_rxfail.svh"
    `include "virtual_sequence/mbtrain/mbtrain_linkspeed_phyretrain_lanepossible_txfail.svh"
    `include "virtual_sequence/mbtrain/mbtrain_linkspeed_phyretrain_nolanepossible_rxfail.svh"
    `include "virtual_sequence/mbtrain/mbtrain_linkspeed_phyretrain_nolanepossible_txfail.svh"
    `include "virtual_sequence/mbtrain/mbtrain_linkspeed_repair_fail_0_3_8_15.svh"
    `include "virtual_sequence/mbtrain/mbtrain_linkspeed_repair_fail_0_7.svh"
    `include "virtual_sequence/mbtrain/mbtrain_linkspeed_repair_fail_4_15.svh"
    `include "virtual_sequence/mbtrain/mbtrain_linkspeed_repair_fail_8_15.svh"
    `include "virtual_sequence/mbtrain/mbtrain_linkspeed_repair_trainerror.svh"
    `include "virtual_sequence/mbtrain/mbtrain_linkspeed_speeddegrade_rxinit.svh"
    `include "virtual_sequence/mbtrain/mbtrain_linkspeed_speeddegrade_txinit.svh"
    `include "virtual_sequence/mbtrain/mbtrain_linkspeed_success.svh"
    `include "virtual_sequence/mbtrain/mbtrain_rxclkcal_success.svh"
    `include "virtual_sequence/mbtrain/mbtrain_rxclkcal_timeout.svh"
    `include "virtual_sequence/mbtrain/mbtrain_rxclkcal_trainerror.svh"
    `include "virtual_sequence/mbtrain/mbtrain_rxdeskew_success.svh"
    `include "virtual_sequence/mbtrain/mbtrain_rxdeskew_timeout.svh"
    `include "virtual_sequence/mbtrain/mbtrain_rxdeskew_trainerror.svh"
    `include "virtual_sequence/mbtrain/mbtrain_valtraincenter_success.svh"
    `include "virtual_sequence/mbtrain/mbtrain_valtraincenter_timeout.svh"
    `include "virtual_sequence/mbtrain/mbtrain_valtraincenter_trainerror.svh"
    `include "virtual_sequence/mbtrain/mbtrain_valtrainvref_success.svh"
    `include "virtual_sequence/mbtrain/mbtrain_valtrainvref_looptillerror.svh"
    `include "virtual_sequence/mbtrain/mbtrain_valtrainvref_timeout.svh"
    `include "virtual_sequence/mbtrain/mbtrain_valtrainvref_trainerror.svh"
    `include "virtual_sequence/mbtrain/mbtrain_valvref_looptillerror.svh"
    `include "virtual_sequence/mbtrain/mbtrain_valvref_success.svh"
    `include "virtual_sequence/mbtrain/mbtrain_valvref_timeout.svh"
    `include "virtual_sequence/mbtrain/mbtrain_valvref_trainerror.svh"
    `include "virtual_sequence/mbtrain/mbtrain_success.svh"
    
    
    // Tests    
    `include "MBTRAIN_test.svh"
    
endpackage : LTSM_pkg
